### ISSUE TITLE
S3_ENDPOINT_URL variable name is incorrect

### ISSUE THREAD

**Issue by McGill-Services** [peterrus/docker-s3-cron-backup#12]
Specifying a S3_ENDPOINT_URL environment variable wasn't working until I changed it to S3_ENDPOINT

**Comment by kitobelix** [comment]
May I add that AWS_ACCESS_KEY_ID is also the correct environment variable, according to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html.

Thanks a lot!

**Comment by peterrus** [comment]
This seems to be fixed!
