### ISSUE TITLE
Docker version tags

### ISSUE THREAD

**Issue by julian-eggers** [peterrus/docker-s3-cron-backup#5]
Hi Peter,

it would be nice when you could create a docker version tag. 

We want to use the backup container in several places and thus avoid future update problems due to a latest tag.

Greetings

**Comment by peterrus** [comment]
Hi Julian,

Great suggestion. I have rebuilt and tagged the current version manually for now but I should probably set up something a bit more automated (like https://medium.com/travis-on-docker/how-to-version-your-docker-images-1d5c577ebf54). I will do that as soon as I push a new version.
