### ISSUE TITLE
Little enhancement

### ISSUE THREAD

**Issue by stex79** [peterrus/docker-s3-cron-backup#8]
Hi I have done a little enhancement makes it easier to use this image as sidecar in k8s.

these are the differences if you want to use them:

```
#!/bin/sh

# default storage class to standard if not provided
S3_STORAGE_CLASS=${S3_STORAGE_CLASS:-STANDARD}

# generate file name for tar
FILE_NAME=/tmp/$BACKUP_NAME-`date "+%Y-%m-%d_%H-%M-%S"`.tar.gz

# Check if TARGET variable is set
if [[ -z ${TARGET} ]];
then
    echo "variable TARGET is not set we use default value"
    TARGET=/data
else
    echo "variable TARGET is set"
fi

echo "creating archive"
tar -zcvf $FILE_NAME $TARGET
echo "uploading archive to S3 [$FILE_NAME, storage class - $S3_STORAGE_CLASS]"
aws s3 cp --storage-class $S3_STORAGE_CLASS $FILE_NAME $S3_BUCKET_URL
echo "removing local archive"
rm $FILE_NAME
echo "done"
```
and added this line in the README:
- TARGET: (Optional, defaults to '/data') Specifies the target location to backup. Useful for sidecar containers and to filter files.

Regards

**Comment by peterrus** [comment]
Hi @stex79, very nice! thanks.

If you want: feel free to open a PR for this. I see no reason for it not to be in the container.

**Comment by stex79** [comment]
Hi,

I have tried to push a feature branch to make a PR, but I am not allowed. How should I do it?

**Comment by peterrus** [comment]
If you fork the repo (in github) you can commit on the master branch of your own forked repo. Github will then ask if you want to create a PR for that.

Let me know if you run into trouble!

-------- Original Message --------
